In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from datetime import datetime

In [7]:
df = pd.read_csv('Yu-Group Data.csv')

In [8]:
df.columns

Index(['Unnamed: 0', 'countyFIPS', 'STATEFP', 'COUNTYFP', 'CountyName',
       'StateName', 'State', 'lat', 'lon', 'POP_LATITUDE', 'POP_LONGITUDE',
       'CensusRegionName', 'CensusDivisionName',
       'Rural-UrbanContinuumCode2013', 'PopulationEstimate2018',
       'PopTotalMale2017', 'PopTotalFemale2017', 'FracMale2017',
       'PopulationEstimate65+2017', 'PopulationDensityperSqMile2010',
       'CensusPopulation2010', 'MedianAge2010', '#EligibleforMedicare2018',
       'MedicareEnrollment,AgedTot2017', '3-YrDiabetes2015-17',
       'DiabetesPercentage', 'HeartDiseaseMortality', 'StrokeMortality',
       'Smokers_Percentage', 'RespMortalityRate2014', '#FTEHospitalTotal2017',
       'TotalM.D.'s,TotNon-FedandFed2017', '#HospParticipatinginNetwork2017',
       '#Hospitals', '#ICU_beds', 'dem_to_rep_ratio', 'PopMale<52010',
       'PopFmle<52010', 'PopMale5-92010', 'PopFmle5-92010', 'PopMale10-142010',
       'PopFmle10-142010', 'PopMale15-192010', 'PopFmle15-192010',
       'PopMale

In [388]:
npi = ['stay at home', '>50 gatherings','>500 gatherings', 'public schools', 'restaurant dine-in','entertainment/gym', 'federal guidelines', 'foreign travel ban']
npi_df = df[npi]
npi_df

stay at home  >50 gatherings  >500 gatherings  public schools  \
0         737519.0        737504.0         737497.0        737500.0   
1         737519.0        737504.0         737497.0        737500.0   
2         737519.0        737504.0         737497.0        737500.0   
3         737519.0        737504.0         737497.0        737500.0   
4         737519.0        737504.0         737497.0        737500.0   
...            ...             ...              ...             ...   
3239      737509.0        737509.0         737509.0        737507.0   
3240           NaN             NaN              NaN        737500.0   
3241           NaN             NaN              NaN        737500.0   
3242           NaN             NaN              NaN             NaN   
3243           NaN             NaN              NaN             NaN   

      restaurant dine-in  entertainment/gym  federal guidelines  \
0               737503.0           737512.0            737500.0   
1               737503.0           737512.0            737500.0   
2               737503.0           737512.0            737500.0   
3               737503.0           737512.0            737500.0   
4               737503.0           737512.0            737500.0   
...                  ...                ...                 ...   
3239            737504.0           737509.0            737500.0   
3240            737499.0           737499.0            737500.0   
3241            737499.0           737499.0            737500.0   
3242                 NaN                NaN                 NaN   
3243                 NaN                NaN                 NaN   

      foreign travel ban  
0               737495.0  
1               737495.0  
2               737495.0  
3               737495.0  
4               737495.0  
...                  ...  
3239            737495.0  
3240            737495.0  
3241            737495.0  
3242                 NaN  
3243                 NaN  

[3244 rows x 8 columns]

In [11]:
datetime.fromordinal(int(npi_df['stay at home'][0]))

datetime.datetime(2020, 4, 4, 0, 0)

In [12]:
from collections import Counter

In [13]:
Counter(npi_df['federal guidelines'])

Counter({737500.0: 3219,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1})

In [14]:
fed_date = 737500

In [15]:
datetime.fromordinal(737501)

datetime.datetime(2020, 3, 17, 0, 0)

In [16]:
(npi_df['stay at home'] - fed_date).min()

3.0

In [17]:
(npi_df['>50 gatherings'] - fed_date).min()

-1.0

In [18]:
(npi_df['>500 gatherings'] - fed_date).min()

-5.0

In [19]:
(npi_df['restaurant dine-in'] - fed_date).min()

-4.0

In [20]:
(npi_df['entertainment/gym'] - fed_date).min()

-4.0

In [21]:
(npi_df['public schools'] - fed_date).min()

-1.0

In [22]:
df.columns

Index(['Unnamed: 0', 'countyFIPS', 'STATEFP', 'COUNTYFP', 'CountyName',
       'StateName', 'State', 'lat', 'lon', 'POP_LATITUDE', 'POP_LONGITUDE',
       'CensusRegionName', 'CensusDivisionName',
       'Rural-UrbanContinuumCode2013', 'PopulationEstimate2018',
       'PopTotalMale2017', 'PopTotalFemale2017', 'FracMale2017',
       'PopulationEstimate65+2017', 'PopulationDensityperSqMile2010',
       'CensusPopulation2010', 'MedianAge2010', '#EligibleforMedicare2018',
       'MedicareEnrollment,AgedTot2017', '3-YrDiabetes2015-17',
       'DiabetesPercentage', 'HeartDiseaseMortality', 'StrokeMortality',
       'Smokers_Percentage', 'RespMortalityRate2014', '#FTEHospitalTotal2017',
       'TotalM.D.'s,TotNon-FedandFed2017', '#HospParticipatinginNetwork2017',
       '#Hospitals', '#ICU_beds', 'dem_to_rep_ratio', 'PopMale<52010',
       'PopFmle<52010', 'PopMale5-92010', 'PopFmle5-92010', 'PopMale10-142010',
       'PopFmle10-142010', 'PopMale15-192010', 'PopFmle15-192010',
       'PopMale

In [23]:
dfmaster = pd.read_csv('master_yu.csv')
dfmaster.head()

Unnamed: 0  death_rate  Unnamed: 0.1  STATEFP  COUNTYFP  CountyName  \
0       10001   20.162419           313       10         1        Kent   
1       10003   16.269320           314       10         3  New Castle   
2       10005   37.507741           315       10         5      Sussex   
3       11001   43.276794           316       11         1  Washington   
4       12001    1.852154           317       12         1     Alachua   

  StateName                 State        lat        lon  ...  >500 gatherings  \
0        DE              Delaware  39.087654 -75.573876  ...         737508.0   
1        DE              Delaware  39.583358 -75.655191  ...         737508.0   
2        DE              Delaware  38.665735 -75.406689  ...         737508.0   
3        DC  District Of Columbia  38.910787 -77.034099  ...         737509.0   
4        FL               Florida  29.669178 -82.357751  ...         737501.0   

   public schools restaurant dine-in entertainment/gym  federal guidelines  \
0          737500             737496          737496.0              737500   
1          737500             737496          737496.0              737500   
2          737500             737496          737496.0              737500   
3          737500             737500          737500.0              737500   
4          737500             737504          737504.0              737500   

   foreign travel ban  SVIPercentile  HPSAShortage  HPSAServedPop  \
0              737495         0.7268         17.66            0.0   
1              737495         0.3761           NaN            NaN   
2              737495         0.4019         21.79            0.0   
3              737495         0.5965           NaN            NaN   
4              737495         0.4729         29.84        12780.0   

   HPSAUnderservedPop  
0             52966.0  
1                 NaN  
2             65373.0  
3                 NaN  
4             89514.0  

[5 rows x 89 columns]

In [395]:
(npi_df['entertainment/gym'][3242]-3) < 0 #making sure NaN values will not be labeled as True

False

In [65]:
scores=[]
for i in range(len(dfmaster)):
    indiv_score = []
    if(dfmaster['>50 gatherings'][i] - fed_date < 0):
        indiv_score.append(1)
    else:
        indiv_score.append(0)
    if(dfmaster['>500 gatherings'][i] - fed_date < 0):
        indiv_score.append(1)
    else:
        indiv_score.append(0)
    if(dfmaster['restaurant dine-in'][i] - fed_date < 0):
        indiv_score.append(1)
    else:
        indiv_score.append(0)
    if(dfmaster['entertainment/gym'][i] - fed_date < 0):
        indiv_score.append(1)
    else:
        indiv_score.append(0)
    if(dfmaster['public schools'][i] - fed_date < 0):
        indiv_score.append(1)
    else:
        indiv_score.append(0)
    if(sum(indiv_score) > 0):
        scores.append(1)
    else:
        scores.append(0)

In [66]:
Counter(scores)

Counter({1: 825, 0: 2000})

In [67]:
dfmaster['Score'] = scores
dfmaster=dfmaster.fillna(0)

In [68]:
dfmaster.columns

Index(['Unnamed: 0', 'death_rate', 'Unnamed: 0.1', 'STATEFP', 'COUNTYFP',
       'CountyName', 'StateName', 'State', 'lat', 'lon', 'POP_LATITUDE',
       'POP_LONGITUDE', 'CensusRegionName', 'CensusDivisionName',
       'Rural-UrbanContinuumCode2013', 'PopulationEstimate2018',
       'PopTotalMale2017', 'PopTotalFemale2017', 'FracMale2017',
       'PopulationEstimate65+2017', 'PopulationDensityperSqMile2010',
       'CensusPopulation2010', 'MedianAge2010', '#EligibleforMedicare2018',
       'MedicareEnrollment,AgedTot2017', '3-YrDiabetes2015-17',
       'DiabetesPercentage', 'HeartDiseaseMortality', 'StrokeMortality',
       'Smokers_Percentage', 'RespMortalityRate2014', '#FTEHospitalTotal2017',
       'TotalM.D.'s,TotNon-FedandFed2017', '#HospParticipatinginNetwork2017',
       '#Hospitals', '#ICU_beds', 'dem_to_rep_ratio', 'PopMale<52010',
       'PopFmle<52010', 'PopMale5-92010', 'PopFmle5-92010', 'PopMale10-142010',
       'PopFmle10-142010', 'PopMale15-192010', 'PopFmle15-192010',

In [31]:
numerical_estimators2=['death_rate','PopulationEstimate2018',
       'PopTotalMale2017', 'PopTotalFemale2017', 'FracMale2017',
       'PopulationEstimate65+2017', 'PopulationDensityperSqMile2010',
       'CensusPopulation2010', 'MedianAge2010', '#EligibleforMedicare2018',
       'MedicareEnrollment,AgedTot2017', '3-YrDiabetes2015-17',
       'DiabetesPercentage', 'HeartDiseaseMortality', 'StrokeMortality',
       'Smokers_Percentage', 'RespMortalityRate2014', '#FTEHospitalTotal2017', "TotalM.D.'s,TotNon-FedandFed2017",'#HospParticipatinginNetwork2017',
       '#Hospitals', '#ICU_beds', 'dem_to_rep_ratio', 'PopMale<52010','PopFmle<52010', 'PopMale5-92010', 'PopFmle5-92010', 'PopMale10-142010', 'PopFmle10-142010', 'PopMale15-192010', 'PopFmle15-192010',
       'PopMale20-242010', 'PopFmle20-242010', 'PopMale25-292010','PopFmle25-292010', 'PopMale30-342010', 'PopFmle30-342010',
       'PopMale35-442010', 'PopFmle35-442010', 'PopMale45-542010', 'PopFmle45-542010', 'PopMale55-592010', 'PopFmle55-592010',
       'PopMale60-642010', 'PopFmle60-642010', 'PopMale65-742010','PopFmle65-742010', 'PopMale75-842010', 'PopFmle75-842010',    'PopMale>842010', 'PopFmle>842010', '3-YrMortalityAge<1Year2015-17',
       '3-YrMortalityAge1-4Years2015-17', '3-YrMortalityAge5-14Years2015-17',
       '3-YrMortalityAge15-24Years2015-17','3-YrMortalityAge25-34Years2015-17',    '3-YrMortalityAge35-44Years2015-17', '3-YrMortalityAge45-54Years2015-17','3-YrMortalityAge55-64Years2015-17', '3-YrMortalityAge65-74Years2015-17',
       '3-YrMortalityAge75-84Years2015-17', '3-YrMortalityAge85+Years2015-17', 'mortality2015-17Estimated' ]

In [33]:
X_train, X_test, y_train, y_test = train_test_split(dfmaster[numerical_estimators], dfmaster['Score'], test_size=0.3)

In [34]:
RFmod = RandomForestClassifier(max_depth=7, n_estimators=7, max_features=5)
RFmod.fit(X_train,np.ravel(y_train))
RFmod.score(X_test,y_test),RFmod.score(X_train,y_train)

(0.7488207547169812, 0.8376327769347496)

In [35]:
RFmod.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 7,
 'max_features': 5,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 7,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [36]:
yhat = RFmod.predict(X_test)
confusion_matrix(y_test,yhat)

array([[603,  26],
       [187,  32]])

# The good stuff, ignore model construction above

In [297]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

In [256]:
X_train, X_test, y_train, y_test = train_test_split(dfmaster[numerical_estimators2], dfmaster['Score'], test_size=0.3)

In [306]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 600, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(1, 20, num = 10)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

random_grid

{'n_estimators': [100, 155, 211, 266, 322, 377, 433, 488, 544, 600],
 'max_features': ['auto', 'sqrt'],
 'max_depth': [1, 3, 5, 7, 9, 11, 13, 15, 17, 20, None],
 'min_samples_split': [2, 5],
 'min_samples_leaf': [1, 2, 4],
 'bootstrap': [False]}

In [307]:
param_grid = random_grid #conducted RandomizedSearchCV, then conducted GridSearchCV after one finely tuned list of parameters

In [308]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_gridsearch = GridSearchCV(estimator = rf, param_grid = param_grid, cv = 3, verbose=2, n_jobs = -1)
# Fit the random search model
rf_gridsearch.fit(X_train, y_train)

Fitting 3 folds for each of 1320 candidates, totalling 3960 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   18.2s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 357 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-1)]: Done 640 tasks      | elapsed:  4.7min
[Parallel(n_jobs=-1)]: Done 1005 tasks      | elapsed:  8.6min
[Parallel(n_jobs=-1)]: Done 1450 tasks      | elapsed: 14.6min
[Parallel(n_jobs=-1)]: Done 1977 tasks      | elapsed: 23.3min
[Parallel(n_jobs=-1)]: Done 2584 tasks      | elapsed: 32.5min
[Parallel(n_jobs=-1)]: Done 3273 tasks      | elapsed: 43.2min
[Parallel(n_jobs=-1)]: Done 3960 out of 3960 | elapsed: 55.5min finished


GridSearchCV(cv=3, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,...
                                              random_state=None, verbose=0,
                                   

In [309]:
rf_gridsearch.best_params_

{'bootstrap': False,
 'max_depth': 17,
 'max_features': 'auto',
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'n_estimators': 100}

In [412]:
RFmod = RandomForestClassifier(n_estimators = 100, min_samples_split = 5, min_samples_leaf = 1, 
                               max_features = 'auto', max_depth = 17, bootstrap = False)
RFmod.fit(X_train, y_train)
#RFmod = rf_random.best_estimator_
RFmod.score(X_test,y_test), RFmod.score(X_train,y_train)

(0.7747641509433962, 1.0)

In [413]:
RFmod.feature_importances_

array([0.03029918, 0.05270752, 0.04818924, 0.0684342 , 0.0525628 ,
       0.07314626, 0.07520865, 0.12533651, 0.06642836, 0.03766975,
       0.03951294, 0.01147579, 0.01790334, 0.03627936, 0.03440494,
       0.03817393, 0.01128978, 0.01387764, 0.02352606, 0.03052166,
       0.03347393, 0.03498566, 0.04459249])

In [414]:
node_purity = pd.DataFrame(numerical_estimators2)
node_purity['purity'] = RFmod.feature_importances_

In [415]:
node_purity.sort_values(by=['purity'],ascending = False)[:10]

0    purity
7                 Smokers_Percentage  0.125337
6                    StrokeMortality  0.075209
5              HeartDiseaseMortality  0.073146
3     PopulationDensityperSqMile2010  0.068434
8              RespMortalityRate2014  0.066428
1             PopulationEstimate2018  0.052708
4                 DiabetesPercentage  0.052563
2          PopulationEstimate65+2017  0.048189
22   3-YrMortalityAge85+Years2015-17  0.044592
10  TotalM.D.'s,TotNon-FedandFed2017  0.039513

In [416]:
yhat = RFmod.predict(X_test)

In [417]:
confusion_matrix(y_test,yhat)

array([[565,  38],
       [153,  92]])

In [418]:
tp = confusion_matrix(y_test,yhat)[1][1]
tn = confusion_matrix(y_test,yhat)[0][0]
fp = confusion_matrix(y_test,yhat)[0][1]
fn = confusion_matrix(y_test,yhat)[1][0]

In [419]:
tpr = tp/(tp+fn)
tpr

0.37551020408163266

In [420]:
tnr = tn/(tn+fp) 
tnr

0.9369817578772802

In [421]:
goodsubset = list(node_purity.sort_values(by=['purity'],ascending = False)[:5][0])

In [422]:
goodsubset

['Smokers_Percentage',
 'StrokeMortality',
 'HeartDiseaseMortality',
 'PopulationDensityperSqMile2010',
 'RespMortalityRate2014']

In [423]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(dfmaster[goodsubset], dfmaster['Score'], test_size=0.3)

In [424]:
simpRFmod = RandomForestClassifier()
simpRFmod.fit(X_train2,y_train2)
simpRFmod.score(X_test2,y_test2), simpRFmod.score(X_train2,y_train2)

(0.7476415094339622, 1.0)

In [425]:
simp_yhat = simpRFmod.predict(X_test2)
confusion_matrix(y_test2,simp_yhat)

array([[554,  49],
       [165,  80]])

In [426]:
tp = confusion_matrix(y_test2,simp_yhat)[1][1]
tn = confusion_matrix(y_test2,simp_yhat)[0][0]
fp = confusion_matrix(y_test2,simp_yhat)[0][1]
fn = confusion_matrix(y_test2,simp_yhat)[1][0]

In [427]:
tpr = tp/(tp+fn)
tpr

0.32653061224489793

In [428]:
tnr = tn/(tn+fp)
tnr

0.9187396351575456